### Ghi chú
GET http://localhost:8080
### Đọc nội dung từ tập tin 
GET http://localhost:8080/LIST_TIVI
###
GET http://localhost:8080/LIST_MOBILE
###
GET http://localhost:8080/LIST_FOOD
###
GET http://localhost:8080/LIST_STORE
### GET Images
GET http://localhost:8080/CA_PHE_1.png
###
POST http://localhost:8080/LOGIN
Content-Type: "application/json"

{
    "Ten_Dang_nhap": "NV_1",
    "Mat_khau": "NV_1"
}
###
POST http://localhost:8080/INSERT_USER
Content-Type: "application/json"

{
        "Ho_ten": "Lập trình javaScript",
        "Ma_so": "QL_101",
        "Ten_Dang_nhap": "javascript",
        "Mat_khau": "js@123",
        "Nhom_Nguoi_dung": {
            "Ten": "Nhân viên Quản lý",
            "Ma_so": "NHAN_VIEN_QUAN_LY"
        }
}
###
PUT http://localhost:8080/UPDATE_USER
Content-Type: "application/json"

{
    "Ma_so": "QL_101",
    "Ho_ten": "Nguyễn Văn An",
    "Ten_Dang_nhap": "nvan",
    "Mat_khau": "an@789"
}
###
DELETE http://localhost:8080/DELETE_USER
Content-Type: "application/json"

{
    "Ma_so": "QL_101"
}
